spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8001
          predicates:
            - Path=/api/auth/**
        - id: user-service
          uri: http://localhost:8002
          predicates:
            - Path=/api/users/**
        - id: approval-service
          uri: http://localhost:8003
          predicates:
            - Path=/api/approvals/**
        - id: role-service
          uri: http://localhost:8004
          predicates:
            - Path=/api/roles/**
        - id: styles-service
          uri: http://localhost:8007
          predicates:
            - Path=/api/inventory/styles,/api/inventory/styles/**
        - id: styles-service-docs
          uri: http://localhost:8007
          predicates:
            - Path=/api/styles/v3/api-docs
          filters:
            - RewritePath=/api/styles/v3/api-docs, /api/inventory/v3/api-docs
        - id: flow-service
          uri: http://localhost:8008
          predicates:
            - Path=/api/flows,/api/flows/**
        - id: flow-service-docs
          uri: http://localhost:8008
          predicates:
            - Path=/api/flow/v3/api-docs
          filters:
            - RewritePath=/api/flow/v3/api-docs, /api/flows/v3/api-docs
        - id: inventory-service
          uri: http://localhost:8005
          predicates:
            - Path=/api/inventory/**
        - id: health-service
          uri: http://localhost:8006
          predicates:
            - Path=/api/health/**

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false
